on:
  push:
    paths:
      - '.github/workflows/lacework-sast-scheduled.yaml'

permissions:
  contents: read
  pull-requests: write
  security-events: write
  actions: read

env:
  LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_CAT }}
  LW_API_KEY: ${{ secrets.LW_API_KEY_CAT }}
  LW_API_SECRET: ${{ secrets.LW_API_SECRET_CAT }}

name: Lacework SAST (Scheduled)
jobs:
  run-analysis:
    runs-on: ubuntu-22.04
    name: Run analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build JAR file
        run: mvn --quiet clean package

      - name: Analyze
        uses: lacework/code-security-action@v1
        with:
          target: push
          tools: sast
          classpath: target/webgoat-2023.5-SNAPSHOT.jar

      - name: Check SARIF file
        run: cat sast.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sast.sarif
          category: Lacework SAST
