on: [push]

permissions:
  contents: read
  pull-requests: write

env:
  LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_CAT }}
  LW_API_KEY: ${{ secrets.LW_API_KEY_CAT }}
  LW_API_SECRET: ${{ secrets.LW_API_SECRET_CAT }}

name: Lacework SCA (Push)
jobs:
  run-analysis:
    runs-on: ubuntu-22.04
    name: Run analysis
    strategy:
      matrix:
        target: [new, old]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Checkout old
        if: ${{ matrix.target == 'old' }}
        run: git checkout HEAD^1

      - name: Run SCA
        uses: lacework/code-security-action@v1
        with:
          target: ${{ matrix.target }}
          tools: sca

  display-results:
    runs-on: ubuntu-22.04
    name: Display SCA results
    needs:
      - run-analysis
    steps:
      - name: Results
        uses: lacework/code-security-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
